### ISSUE TITLE
Feature request: Move LUT to "logical function" conversion code into a library

### ISSUE THREAD

**Issue by mithro** [whitequark/icefloorplan#5]
It would be really nice to have a decent C++ library for doing the process of converting the lookup table back to the "logical function" it is performing.

**Comment by mithro** [comment]
You mentioned on IRC that for the iCE40 this was a lot simpler then you thought but I didn't really understand what you were saying. It would be nice to have this seperated from the GUI code...

**Comment by whitequark** [comment]
This is a [~50-line function](https://github.com/whitequark/icefloorplan/blob/8e71c226424b91074278f00b0cadef5c21e977db/floorplanbuilder.cpp#L55-L141) with no dependencies. I don't think such things should exist as libraries, just copy and paste, especially given that everyone has their own opinion on the output presentation, and this can't really be separated from the logic here.
